// Run with Playwright installed, or set PLAYWRIGHT_MODULE to an existing install.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.SANDBOX_URL || 'http://127.0.0.1:4173';

(async () => {
  fs.mkdirSync('.preview', { recursive: true });
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const requests = [], errors = [];
    page.on('request', request => requests.push(request.url()));
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(base, { waitUntil: 'networkidle' });
    const sandbox = page.locator('#sandbox');
    await sandbox.scrollIntoViewIfNeeded();
    assert.equal(await sandbox.locator('iframe').count(), 0);
    assert.equal(requests.some(url => /SandboxWorkspace/.test(url)), false, 'Workspace must not load before open');
    await sandbox.screenshot({ path: '.preview/sandbox-closed.png' });
    await sandbox.getByRole('button', { name: 'Open sandbox' }).click();
    await page.locator('#sandbox-command').waitFor();
    assert.ok(requests.some(url => /SandboxWorkspace/.test(url)));
    assert.equal(await page.locator('#sandbox-command').evaluate(node => node === document.activeElement), true);
    await sandbox.screenshot({ path: '.preview/sandbox-explore.png' });
    const command = page.locator('#sandbox-command');
    const run = async value => { await command.fill(value); await command.press('Enter'); };
    await run('cd learning');
    await run('cat react.txt');
    assert.match(await page.locator('.computer-screen').innerText(), /Component architecture/);
    await command.fill('my draft');
    await command.press('ArrowUp'); assert.equal(await command.inputValue(), 'cat react.txt');
    await command.press('ArrowDown'); assert.equal(await command.inputValue(), 'my draft');
    await run('<img src=x onerror=alert(1)>');
    assert.equal(await sandbox.locator('.computer-screen img').count(), 0);
    await run('theme cream');
    assert.equal(await page.locator('.sandbox-cream').count(), 1);
    await run('theme charcoal');
    await run('edit postcard');
    const html = page.locator('#sandbox-html'), css = page.locator('#sandbox-css');
    assert.equal(await page.locator('#sandbox-example').inputValue(), 'postcard');
    assert.equal(await page.locator('#sandbox-example').evaluate(node => node === document.activeElement), true);
    const iframe = () => page.frameLocator('iframe[title="Your HTML and CSS experiment"]');
    await html.fill('<h1 class="hello">Hello Monterrey</h1>');
    assert.equal(await iframe().getByText('Hello Monterrey').count(), 0);
    await page.getByRole('button', { name: 'Run preview' }).click();
    await iframe().getByText('Hello Monterrey').waitFor();
    await page.getByRole('button', { name: 'Reset example' }).click();
    assert.match(await html.inputValue(), /postcard/);
    await page.getByRole('button', { name: 'Undo reset' }).click();
    assert.match(await html.inputValue(), /Hello Monterrey/);
    await page.locator('#sandbox-example').selectOption('button');
    await page.locator('#sandbox-example').selectOption('postcard');
    assert.match(await html.inputValue(), /Hello Monterrey/);
    await page.getByRole('button', { name: 'Close sandbox', exact: false }).first().click();
    await sandbox.locator('iframe').waitFor({ state: 'detached' });
    assert.equal(await sandbox.locator('iframe').count(), 0);
    assert.equal(await page.getByRole('button', { name: 'Open sandbox' }).evaluate(node => node === document.activeElement), true);
    await page.getByRole('button', { name: 'Open sandbox' }).click();
    await html.waitFor();
    assert.match(await html.inputValue(), /Hello Monterrey/);
    await page.getByRole('button', { name: 'Reset example' }).click();
    await iframe().locator('.postcard').waitFor();
    await sandbox.screenshot({ path: '.preview/sandbox-make.png' });

    // Hostile HTML and CSS must remain inside an inert, network-free preview.
    const unexpected = [];
    await page.route('https://sandbox-test.invalid/**', route => { unexpected.push(route.request().url()); return route.abort(); });
    await html.fill('<script>parent.__escaped=true</script><img src="https://sandbox-test.invalid/a" onerror="parent.__escaped=true"><meta http-equiv="refresh" content="0;url=https://sandbox-test.invalid/go"><base href="https://sandbox-test.invalid/"><iframe src="https://sandbox-test.invalid/frame"></iframe><form action="https://sandbox-test.invalid/post"><button>Submit</button></form><a href="https://sandbox-test.invalid/link">Go</a><svg onload="parent.__escaped=true"></svg><h1 class="safe">Safe content</h1>');
    await css.fill('@import "https://sandbox-test.invalid/style"; .safe { background-image: url("https://sandbox-test.invalid/bg"); } </style><script>parent.__escaped=true</script><meta http-equiv="refresh" content="0;url=https://sandbox-test.invalid/escape">');
    await page.getByRole('button', { name: 'Run preview' }).click();
    await iframe().getByText('Safe content').waitFor();
    await page.waitForTimeout(400);
    assert.equal(await page.evaluate(() => window.__escaped), undefined);
    assert.equal(await iframe().locator('script,img,iframe,form,a,svg,base,meta[http-equiv="refresh"]').count(), 0);
    assert.deepEqual(unexpected, []);
    assert.equal(await page.locator('iframe').getAttribute('sandbox'), '');
    await iframe().getByRole('button', { name: 'Submit' }).click();
    assert.equal(page.url().startsWith(base), true);

    await page.emulateMedia({ reducedMotion: 'reduce' });
    await html.fill('<p class="motion">Static, please.</p>');
    await css.fill('@keyframes spin { to { transform: rotate(360deg); } } .motion { animation: spin 1s infinite !important; transition: all 1s !important; }');
    await page.getByRole('button', { name: 'Run preview' }).click();
    await iframe().getByText('Static, please.').waitFor();
    assert.equal(await iframe().locator('.motion').evaluate(node => getComputedStyle(node).animationName), 'none');
    assert.equal(await page.locator('.sandbox-workspace').evaluate(node => getComputedStyle(node).animationName), 'none');
    await page.getByRole('button', { name: 'Reset example' }).click();
    await iframe().locator('.postcard').waitFor();
    for (const width of [320, 390, 768, 1440]) {
      await page.setViewportSize({ width, height: 900 });
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Overflow at ${width}px`);
      if (width === 390) await sandbox.screenshot({ path: '.preview/sandbox-mobile.png' });
    }
    await page.getByRole('button', { name: 'Return to terminal' }).click();
    await run('open logistics');
    assert.equal(await page.locator('#p07 h3').evaluate(node => node === document.activeElement), true);
    await sandbox.scrollIntoViewIfNeeded();
    await run('play invaders');
    await page.getByRole('button', { name: 'Start a round' }).waitFor();
    await page.waitForTimeout(350);
    assert.equal(await page.getByRole('button', { name: 'Start a round' }).evaluate(node => node === document.activeElement), true);
    await page.getByRole('button', { name: 'Start a round' }).click();
    await page.waitForTimeout(200);
    await page.getByRole('link', { name: 'Back to the sandbox' }).click();
    await page.getByRole('button', { name: 'Keep playing' }).waitFor({ state: 'attached' });
    const score = await page.locator('.arcade-hud b').first().innerText();
    await run('play invaders');
    await page.waitForTimeout(200);
    assert.equal(await page.locator('.arcade-hud b').first().innerText(), score);
    assert.equal(await page.getByRole('button', { name: 'Keep playing' }).evaluate(node => node === document.activeElement), true);
    assert.deepEqual(errors, []);

    // A failed deferred download leaves the page usable and exposes recovery.
    const retry = await browser.newPage();
    await retry.route('**/SandboxWorkspace-*.js', route => route.abort());
    await retry.goto(base);
    await retry.getByRole('button', { name: 'Open sandbox' }).click();
    await retry.getByRole('button', { name: 'Reload page' }).waitFor();
    await retry.unroute('**/SandboxWorkspace-*.js');
    await Promise.all([retry.waitForEvent('load'), retry.getByRole('button', { name: 'Reload page' }).click()]);
    await retry.getByRole('button', { name: 'Open sandbox' }).click();
    await retry.locator('#sandbox-command').waitFor({ timeout: 5000 });
    await retry.close();
    const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
    await mobile.goto(base);
    await mobile.getByRole('button', { name: 'Open sandbox' }).tap();
    await mobile.getByRole('button', { name: 'studio ↗' }).tap();
    await mobile.locator('#sandbox-example').selectOption('postcard');
    await mobile.locator('iframe').scrollIntoViewIfNeeded();
    await mobile.frameLocator('iframe').locator('.postcard').waitFor();
    await mobile.waitForTimeout(250);
    await mobile.screenshot({ path: '.preview/sandbox-touch-preview.png' });
    await mobile.getByRole('button', { name: 'Run preview' }).tap();
    await mobile.getByRole('button', { name: 'Close sandbox' }).first().tap();
    await mobile.locator('iframe').waitFor({ state: 'detached' });
    await mobile.goto(base + '/?view=original');
    assert.equal(await mobile.locator('#sandbox').count(), 0);
    assert.ok((await mobile.locator('body').innerText()).includes('Jose'));
    await mobile.close();
    console.log('Sandbox lazy loading, commands, drafts/reset, preview containment, reduced motion, widths, focus, arcade bridge and chunk recovery: PASS');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
