import assert from 'node:assert/strict';
import { appendCommand, executeCommand, limits, parseCommand } from '../src/lib/sandbox/commands.js';
import { directories, files, normalizePath } from '../src/lib/sandbox/filesystem.js';
import { projects } from '../src/data/projects.js';
import { learningTopics } from '../src/data/learning.js';
import { HOME, freshHome, readHome, saveFile, validateHome, filesystem } from '../src/lib/sandbox/home.js';
import { completeCommand } from '../src/lib/sandbox/computer.js';

assert.deepEqual(parseCommand('  cat "learning/react.txt" '), ['cat', 'learning/react.txt']);
assert.deepEqual(parseCommand("cat 'about.txt'"), ['cat', 'about.txt']);
assert.match(executeCommand('cat "unfinished').text, /quotation/);
assert.match(executeCommand('x'.repeat(513)).text, /512/);
assert.equal(normalizePath('../../../../about.txt', '/learning'), '/about.txt');
assert.equal(normalizePath('./../projects//', '/learning'), '/projects');
assert.equal(normalizePath('~/learning', '/projects'), '/learning');
assert.equal(executeCommand('cd learning').cwd, '/learning');
assert.equal(executeCommand('cd', '/learning').cwd, '/');
assert.equal(executeCommand('cd /about.txt').cwd, undefined);
assert.match(executeCommand('ls').text, /projects\//);
assert.equal(executeCommand('ls /about.txt').text, 'about.txt');
assert.match(executeCommand('cat react.txt', '/learning').text, /Currently learning/);
assert.match(executeCommand('cat /learning').text, /folder/);
assert.match(executeCommand('cat nowhere').text, /No file/);
assert.match(executeCommand('cat __proto__').text, /No file/);
assert.equal(executeCommand('edit __proto__').action, undefined);
assert.equal(executeCommand('open constructor').action, undefined);
assert.equal(executeCommand('theme cream').action.theme, 'cream');
assert.equal(executeCommand('theme blue').action, undefined);
assert.equal(executeCommand('edit').action.example, 'button');
assert.equal(executeCommand('edit postcard').action.example, 'postcard');
assert.equal(executeCommand('play invaders').action.type, 'arcade');
assert.match(executeCommand('ls | cat').text, /one argument/);
assert.match(executeCommand('sudo').text, /Unknown command/);
assert.match(executeCommand('open logistics').text, /AFH/);
for (const project of projects) {
  const result = executeCommand(`open ${project.slug}`);
  assert.match(result.text, new RegExp(project.name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  assert.ok(files.has(`/projects/${project.slug}.txt`));
  assert.equal(result.links.some(link => link.href.startsWith('http')), project.status === 'live' && Boolean(project.url));
}
for (const topic of learningTopics) {
  assert.ok(executeCommand(`learn ${topic.name.toLowerCase()}`).text.includes(topic.next));
}
assert.ok(directories.has('/experiments/postcard'));
let state = { cwd: '/', history: [], output: [] };
for (let index = 0; index < 230; index++) state = appendCommand(state, `cat ${index}`, { text: 'x'.repeat(7000) });
assert.equal(state.history.length, limits.history);
assert.equal(state.output.length, limits.output);
assert.equal(state.output[0].text.length, limits.entry);
assert.equal(appendCommand(state, 'clear', executeCommand('clear')).output.length, 0);
assert.equal(appendCommand(state, 'cd /learning', executeCommand('cd /learning')).cwd, '/learning');
console.log('Sandbox commands, paths, aliases, shared content, prototype names, history and output bounds: PASS');

let computer = { cwd: HOME, history: [], output: [], home: freshHome() };
const run = value => { const result = executeCommand(value, computer.cwd, computer); computer = appendCommand(computer, value, result); return result; };
assert.match(run('cat readme.txt').text, /mkdir ideas/);
assert.ok(run('ls').listing.some(entry => entry.name === 'projects' && entry.directory));
assert.equal(run('mkdir ideas').error, undefined);
assert.equal(run('echo "a > b" > ideas/notes.txt').error, undefined);
assert.equal(run('cat ideas/notes.txt').text, 'a > b\n');
run('echo "another line" >> ideas/notes.txt');
assert.equal(run('cat ideas/notes.txt').text, 'a > b\nanother line\n');
assert.equal(run('cp ideas/notes.txt ideas/copy.txt').error, undefined);
assert.equal(run('mv ideas/copy.txt ideas/renamed.txt').error, undefined);
assert.equal(run('cp ideas/notes.txt ideas/renamed.txt').error, true);
assert.equal(run('rm ideas').error, true);
run('rm ideas/renamed.txt');
assert.equal(run('cat ideas/renamed.txt').error, true);
assert.equal(run('echo broken > /about.txt').error, true);
assert.equal(run('echo broken > ~/projects/nope.txt').error, true);
assert.equal(run('mkdir /home/guest/../../escape').error, true);
assert.equal(run('touch nowhere/file.txt').error, true);
assert.equal(run('edit hello.js').action.type, 'file');
assert.equal(run('edit /about.txt').action.readOnly, true);
assert.equal(run('run hello.js').action.type, 'run');
assert.equal(run('run readme.txt').error, true);
assert.equal(run('js [1,2].map(n => n * 2)').action.code, '[1,2].map(n => n * 2)');
assert.equal(run('download ideas/notes.txt').action.content, 'a > b\nanother line\n');
assert.deepEqual(completeCommand('cat read', computer), ['cat readme.txt']);
assert.deepEqual(completeCommand('cd lear', computer), ['cd learning/']);
assert.equal(run('cd ideas').cwd, HOME + '/ideas');
assert.equal(run('rm ../ideas').error, true);
assert.equal(run('cd').cwd, HOME);
assert.equal(run('pwd').text, HOME);
assert.equal(run('whoami').text, 'guest');
assert.ok(run('history').text.includes('cat readme.txt'));
assert.ok(run('tree').text.includes('notes.txt'));
assert.equal(run('touch __proto__').error, undefined);
assert.ok(filesystem(computer.home).files.has(HOME + '/__proto__'));
assert.throws(() => saveFile(computer.home, HOME + '/large.txt', 'x'.repeat(20481)), /20 KB/);
assert.throws(() => validateHome({ files: [[HOME + '/../escape', 'bad']], dirs: [HOME] }), /path/);
assert.equal(readHome({ getItem() { throw new Error('Blocked'); } }).persistence, 'session');
assert.equal(readHome({ getItem: () => '{broken' }).persistence, 'session');
assert.deepEqual(readHome({ getItem: () => JSON.stringify(computer.home) }).home, computer.home);
console.log('Writable home, persistence validation, file operations, read-only mounts, completion, and JavaScript dispatch: PASS');
